repos:
- repo: https://github.com/adrienverge/yamllint
  hooks:
  - id: yamllint
    args:
    - --format
    - parsable
    - --strict
  rev: v1.32.0
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  hooks:
  - id: yamlfmt
    args:
    - --width
    - '120'
    - --implicit_start
    - --implicit_end
    - --mapping
    - '2'
    - --sequence
    - '2'
    - --offset
    - '0'
  rev: 0.2.3
ci:
  autoupdate_schedule: quarterly
